client_max_body_size 10M;

server {
    listen 127.0.0.1:8080;
    server_name localhost;
    error_page 403 ./www/error_pages/403.html;
    error_page 404 ./www/error_pages/404.html;
    error_page 500 ./www/error_pages/500.html;

    location / {
        root ./www/;
        index index.html;
        autoindex on;
        allowed_methods GET;
        cgi_extensions .py .php;
    }
    location /images {
        root ./www/alt/images/;
        index index.html;
        autoindex off;
        allowed_methods GET;
    }
    location /upload {
        root ./www/upload/;
        autoindex on;
        allowed_methods POST GET DELETE;
        upload_path ./www/upload;
        client_max_body_size 20M;
    }
    cgi {
        extension .py;
        path /usr/bin/python3;
    }
    cgi {
        extension .php;
        path /usr/bin/php;
    }
}

server {
    listen 0.0.0.0:8081;
    server_name test_server;
    error_page 404 ./www/error_pages/404.html;
    location / {
        root ./www/;
        index index.html;
        autoindex off;
        allowed_methods GET;
    }
}
